#!/usr/bin/env bash
# ============================================================================
# AI Dev Toolkit - Project Agent Setup Template
# This file is generated by /refresh-context workflow
#
# 🚨 ABSOLUTE RULE: NEVER OVERWRITE `.agent/setup.sh`. MERGE ONLY.
# You are ONLY allowed to ADD or REMOVE entries in REQUIRED_SKILLS=(...).
# ============================================================================
set -euo pipefail

# Parse --force flag
FORCE_WORKFLOWS=false
for arg in "$@"; do [ "$arg" = "--force" ] && FORCE_WORKFLOWS=true; done

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SKILLS_DIR="$SCRIPT_DIR/skills"

echo "================================================="
echo "🤖 AI Agent Project Setup - $(basename "$PROJECT_DIR")"
echo "================================================="

# The __INJECT_REQUIRED_SKILLS__ placeholder will be replaced by the AI Workflow
REQUIRED_SKILLS=(
  __INJECT_REQUIRED_SKILLS__
)

# -- Step 1: Install Skills via NPX -----------------------------------------
# Isolate npm cache to prevent permissions errors (EPERM) from corrupted global installs
export npm_config_cache="/tmp/ai-agent-npm-cache"

echo "Checking npx skills CLI..."
if ! command -v npx &> /dev/null; then
    echo "❌ Error: npx is not installed. Please install Node.js."
    exit 1
fi

echo "Installing required skills via npx skills..."
MISSING=0
for skill in "${REQUIRED_SKILLS[@]}"; do
  if [ -n "$skill" ] && [ "$skill" != "__INJECT_REQUIRED_SKILLS__" ]; then
    echo "  🔄 Installing $skill..."
    if ! npx -y skills add "$skill" -y; then
       echo "  ❌ Failed to install $skill"
       MISSING=1
    fi
  fi
done

echo "Checking for updates to existing skills..."
npx -y skills update -y || echo "  ⚠️ Update check failed or skipped."

if [ ! -f "$SKILLS_DIR/project-context/SKILL.md" ]; then
  echo ""
  echo "⚠️  CRITICAL: 'project-context' skill is missing."
  echo "👉 Please run the '/refresh-context' workflow in your AI agent to generate it."
fi

# -- Step 2: Cross-IDE symlinks (Fallback) ----------------------------------
# Note: npx skills attempts to link automatically, but we ensure project-local
# tooling works for Cursor and Claude via these explicit links.
echo ""
echo "Setting up IDE symlinks..."

# Cursor: .cursor/skills -> .agent/skills
mkdir -p "$PROJECT_DIR/.cursor"
if [ ! -L "$PROJECT_DIR/.cursor/skills" ]; then
  ln -sfn "$SKILLS_DIR" "$PROJECT_DIR/.cursor/skills"
  echo "  ✅ .cursor/skills -> .agent/skills"
else
  echo "  ✅ .cursor/skills (already linked)"
fi

# Claude Code: .claude/skills -> .agent/skills
mkdir -p "$PROJECT_DIR/.claude"
if [ ! -L "$PROJECT_DIR/.claude/skills" ]; then
  ln -sfn "$SKILLS_DIR" "$PROJECT_DIR/.claude/skills"
  echo "  ✅ .claude/skills -> .agent/skills"
else
  echo "  ✅ .claude/skills (already linked)"
fi

# -- Step 3: Ensure .agent is tracked in git --------------------------------
echo ""
echo "Checking git tracking..."
GITIGNORE="$PROJECT_DIR/.gitignore"
if [ -f "$GITIGNORE" ] && grep -q "^\.agent" "$GITIGNORE"; then
  echo "  ⚠️  WARNING: .agent is in .gitignore - removing so skills are shared with team"
  sed -i.bak '/^\.agent/d' "$GITIGNORE" && rm -f "$GITIGNORE.bak"
  echo "  ✅ .agent removed from .gitignore"
else
  echo "  ✅ .agent is tracked"
fi

# -- Step 4: Create scaffolding if missing ----------------------------------
echo ""
echo "Checking scaffolding..."
mkdir -p "$SCRIPT_DIR/workflows"
# Clean up legacy workflows from older versions of the toolkit
rm -f "$SCRIPT_DIR/workflows/scan-modules.md"
rm -f "$SCRIPT_DIR/workflows/init-project.md"
mkdir -p "$PROJECT_DIR/docs/modules" "$PROJECT_DIR/docs/_guides"
for wf in "$GLOBAL_TOOLKIT/workflows/"*.md; do
  wf_name=$(basename "$wf")
  target="$SCRIPT_DIR/workflows/$wf_name"
  if [ ! -f "$target" ] || [ "$FORCE_WORKFLOWS" = true ]; then
    cp "$wf" "$target"
    echo "  ✅ $([ "$FORCE_WORKFLOWS" = true ] && echo 'Updated' || echo 'Added'): workflows/$wf_name"
  else
    echo "  ⏭️  Skipped (exists): workflows/$wf_name"
  fi
done
echo "  ✅ Scaffolding ready"

# -- Summary ----------------------------------------------------------------
echo ""
echo "================================================="
if [ "$MISSING" = "1" ]; then
  echo "⚠️ Setup complete with warnings."
  echo "👉 Some skills failed to install. Check your network or npm cache permissions."
else
  echo "🎉 Project AI setup complete! Agent skills are ready."
fi
echo "================================================="
echo ""
